version: '3'
services:
    nginx:
        # 容器名称
        container_name: "compose-nginx"
        image: nginx:latest
        restart: always
        # 端口映射
        ports:
            - "80:80"
            - "443:443"
        environment:
            - TZ=Asia/Shanghai
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "./nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/html:/usr/share/nginx/html"
            - "./nginx/log:/var/log/nginx/"
        networks:
            app_net:
                ipv4_address: 10.10.10.2
    php:
        build: ./php-extension
        image: php:7.4
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - "./nginx/html:/var/www/html"
            - "./php74/etc:/usr/local/etc"
            - "./php74/log:/var/log/php"
        stdin_open: true
        tty: true   #这两条是防止启动php失败
        networks:
            app_net:
                ipv4_address: 10.10.10.3
        environment:
            - TZ=Asia/Shanghai # 设置时区
        container_name: "compose-php74"
networks:
    # 配置docker network
    app_net:
        driver: bridge
        driver_opts:
          com.docker.network.enable_ipv6: "true"
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16
